IDENTIFICADOR(indice) OPERADOR(=) ENTERO(1) SALTO
WHILE IDENTIFICADOR(indice) COMPARADOR(<) ENTERO(31) SEPARADOR SALTO
INDENTA(3) IDENTIFICADOR(otro) OPERADOR(=) BOOLEANO(True) SALTO
IF IDENTIFICADOR(indice) OPERADOR(%) ENTERO(3) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(6) PRINT STRING(fizz) SALTO
IDENTIFICADOR(otro) OPERADOR(=) BOOLEANO(False) SALTO
DEINDENTA(6)
IF IDENTIFICADOR(indice) OPERADOR(%) ENTERO(5) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(6) PRINT STRING(buzz) SALTO
IDENTIFICADOR(otro) OPERADOR(=) BOOLEANO(False) SALTO
DEINDENTA(6)
IF IDENTIFICADOR(otro) SEPARADOR SALTO
INDENTA(6) PRINT IDENTIFICADOR(indice) SALTO
DEINDENTA(6)
PRINT STRING(\n) SALTO
IDENTIFICADOR(indice) OPERADOR(=) IDENTIFICADOR(indice) OPERADOR(+) ENTERO(1) SALTO
DEINDENTA(3)
