IDENTIFICADOR(n) OPERADOR(=) ENTERO(50) SALTO
RESERVADA(if) IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) OPERADOR(==) ENTERO(0) RESERVADA(and) IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) OPERADOR(==) ENTERO(0) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(print) STRING("FizzBuzz\"") SALTO
DEINDENTA(4)
RESERVADA(elif) IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) OPERADOR(==) ENTERO(0) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(print) STRING('Fizz') SALTO
DEINDENTA(4)
RESERVADA(elif) IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) OPERADOR(==) ENTERO(0) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(print) STRING("Buzz") SALTO
DEINDENTA(4)
RESERVADA(else) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(print) IDENTIFICADOR(n) SALTO
DEINDENTA(4)
