IDENTIFICADOR(n) OPERADOR(=) ENTERO(50) SALTO
IF IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) COMPARADOR(==) ENTERO(0) AND IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(4) PRINT STRING(FizzBuzz\") SALTO
DEINDENTA(4)
ELIF IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(4) PRINT STRING(Fizz) SALTO
DEINDENTA(4)
ELIF IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(4) WHILE IDENTIFICADOR(n) COMPARADOR(>) ENTERO(9) SALTO
INDENTA(8) PRINT STRING(Buzz1) SALTO
DEINDENTA(8)
IF ENTERO(0) SALTO
INDENTA(8) IF ENTERO(0) SALTO
INDENTA(12) IF ENTERO(0) SALTO
INDENTA(16) PRINT STRING(Buzz4) SALTO
DEINDENTA(16)
DEINDENTA(12)
DEINDENTA(8)
PRINT STRING(Buzz5) SALTO
DEINDENTA(4)
ELSE SEPARADOR SALTO
INDENTA(4) PRINT IDENTIFICADOR(n) SALTO
DEINDENTA(4)
