IDENTIFICADOR(n) OPERADOR(=) ENTERO(50) SALTO
RESERVADA(if) IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) OPERADOR(==) ENTERO(0) RESERVADA(and) IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) OPERADOR(==) ENTERO(0) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(print) STRING("FizzBuzz\"") SALTO
DEINDENTA(4)
RESERVADA(elif) IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) OPERADOR(==) ENTERO(0) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(print) STRING('Fizz') SALTO
DEINDENTA(4)
RESERVADA(elif) IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) OPERADOR(==) ENTERO(0) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(while) IDENTIFICADOR(n) OPERADOR(>) ENTERO(9) SALTO
INDENTA(8) RESERVADA(print) STRING("Buzz1") SALTO
DEINDENTA(8)
RESERVADA(if) ENTERO(0) SALTO
INDENTA(8) RESERVADA(if) ENTERO(0) SALTO
INDENTA(12) RESERVADA(if) ENTERO(0) SALTO
INDENTA(16) RESERVADA(print) STRING("Buzz4") SALTO
DEINDENTA(16)
DEINDENTA(12)
DEINDENTA(8)
RESERVADA(print) STRING("Buzz5") SALTO
DEINDENTA(4)
RESERVADA(else) SEPARADOR(:) SALTO
INDENTA(4) RESERVADA(print) IDENTIFICADOR(n) SALTO
DEINDENTA(4)
