IDENTIFICADOR(n) OPERADOR(=) ENTERO(50) SALTO
IF IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) COMPARADOR(==) ENTERO(0) AND IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(4) PRINT STRING(FizzBuzz) SALTO
DEINDENTA(4)
ELIF IDENTIFICADOR(n) OPERADOR(%) ENTERO(3) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(4) PRINT STRING(Fizz) SALTO
DEINDENTA(4)
ELIF IDENTIFICADOR(n) OPERADOR(%) ENTERO(5) COMPARADOR(==) ENTERO(0) SEPARADOR SALTO
INDENTA(4) Caracter ilegal <현>. En la linea 9.
